# Autogenerated wrapper script for CSFML_jll for i686-w64-mingw32-cxx03
export libcsfml_audio, libcsfml_graphics, libcsfml_network, libcsfml_system, libcsfml_window

using SFML_jll
JLLWrappers.@generate_wrapper_header("CSFML")
JLLWrappers.@declare_library_product(libcsfml_audio, "csfml-audio-2.dll")
JLLWrappers.@declare_library_product(libcsfml_graphics, "csfml-graphics-2.dll")
JLLWrappers.@declare_library_product(libcsfml_network, "csfml-network-2.dll")
JLLWrappers.@declare_library_product(libcsfml_system, "csfml-system-2.dll")
JLLWrappers.@declare_library_product(libcsfml_window, "csfml-window-2.dll")
function __init__()
    JLLWrappers.@generate_init_header(SFML_jll)
    JLLWrappers.@init_library_product(
        libcsfml_audio,
        "bin\\csfml-audio-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_graphics,
        "bin\\csfml-graphics-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_network,
        "bin\\csfml-network-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_system,
        "bin\\csfml-system-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_window,
        "bin\\csfml-window-2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
