# Autogenerated wrapper script for CSFML_jll for x86_64-apple-darwin
export libcsfml_audio, libcsfml_graphics, libcsfml_network, libcsfml_system, libcsfml_window

using SFML_jll
JLLWrappers.@generate_wrapper_header("CSFML")
JLLWrappers.@declare_library_product(libcsfml_audio, "@rpath/libcsfml-audio.2.5.dylib")
JLLWrappers.@declare_library_product(libcsfml_graphics, "@rpath/libcsfml-graphics.2.5.dylib")
JLLWrappers.@declare_library_product(libcsfml_network, "@rpath/libcsfml-network.2.5.dylib")
JLLWrappers.@declare_library_product(libcsfml_system, "@rpath/libcsfml-system.2.5.dylib")
JLLWrappers.@declare_library_product(libcsfml_window, "@rpath/libcsfml-window.2.5.dylib")
function __init__()
    JLLWrappers.@generate_init_header(SFML_jll)
    JLLWrappers.@init_library_product(
        libcsfml_audio,
        "lib/libcsfml-audio.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_graphics,
        "lib/libcsfml-graphics.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_network,
        "lib/libcsfml-network.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_system,
        "lib/libcsfml-system.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcsfml_window,
        "lib/libcsfml-window.2.5.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
